### ISSUE TITLE
Decompiled files being opened on vscode startup even after uninstalling extension

### ISSUE THREAD

**Issue by raghavg123** [icsharpcode/ilspy-vscode#47] opened 2020-02-19 16:31 UTC
I installed the extension to see what it can do, ran it on a game file dll, which came out pretty well, but then I realized I didn't have any use for it so I uninstalled the extension. But now, on every vscode startup, I get these two files in my editor which are blank, and can't be saved:

![image](https://user-images.githubusercontent.com/14952412/74852680-f45f2d00-5362-11ea-8dda-e92a0b1a2e20.png)

![image](https://user-images.githubusercontent.com/14952412/74852933-3c7e4f80-5363-11ea-9cdb-49e1c532c484.png)

Is there any way to stop this? It's getting pretty annoying.

**Comment by raghavg123** [comment] 2020-02-21 05:49
Interestingly, after wasting over a day on looking up the internet for a similar problem, I've found no solution. I've tried doing a clean reinstall, with no avail. More so, on opening a new window, another window with both files pops up and has to be manually closed. I also created both files in the `C:\` directory and tried saving to them, but nothing works. I'm really getting tired of this stuff and want to abandon vscode for this. Thanks a lot ILSpy.

**Comment by siegfriedpammer** [comment] 2020-02-21 06:55
I can imagine you are frustrated by this! (I would be too!) However I just tried to reproduce this, and it works as expected on my machine.

 As you write you have already tried a clean reinstall of vscode: Have you removed all the configuration files in `%APPDATA%\Code`? Because if you already tried that and the windows still open on every launch, I don't think the problem is related to ILSpy, but there is something wrong with vscode. A clean install with no "memory" of the ilspy extension should not open these files. Are there any other extensions installed that offer features related to handling previously open files or the previous session state?

Without a working repro, we neither are able to fix this, nor could forward this to the vscode developers.

**Comment by siegfriedpammer** [comment] 2020-02-21 07:05
Addedum: Another special directory related to installed extensions is `%USERPROFILE%\.vscode`. Removing that directory might help as well...

**Comment by christophwille** [comment] 2020-02-21 07:58
I tried the following: pick assembly, decompile a member (to get those two files), immediately uninstall ILSpy, close VSCode, re-open it (not doing a thing with the decompiled cs/il windows in the process). Yes, the windows are there on re-opening (that was expected), and they are empty (as per your screenshot). 

Closing the windows (via X and telling VSCode I don't want to save) closes it in the instance, but on closing/re-opening VSCode they are back. That was unexpected but exactly what you are seeing.

Now the question is - VSCode bug or something in the way we opened those windows? @jeremymeng  any idea by chance?

**Comment by raghavg123** [comment] 2020-02-21 12:25
@siegfriedpammer and @christophwille First of all, thank you for responding.

Second of all, sorry for going off on a rant without knowing what I'm talking about. Your tool is amazing and if I ever will learn C# I'll be sure to use it. I just got a bit frustrated and that's all. Again, I'm really sorry and mean no ill-will to the maintainers of this repo.

Third, I seem to either be extremely stupid, or just careless, because while uninstalling VSCode, the `%APPDATA%\Code` directory slipped under my radar. Deleting EVERYTHING in that folder makes everything work fine again.

Thank you, really!

P.S. Should I close this now?

**Comment by christophwille** [comment] 2020-02-21 13:12
This is definitely a bug. Question is are we causing it or simply triggering a bug in VSCode

**Comment by jeremymeng** [comment] 2020-02-22 05:26
Our extension just opens two documents using the VS Code api with the `untitled:` schema. I will try to reproduce it with a new extension from the template then report to the VS Code repo.

**Comment by jeremymeng** [comment] 2020-02-22 05:31
Another thing we could do is to create and use real files under temp folder instead of untitled which seems default to root folder when we attempt  to save them.

Or VS Code shouldn't default their saving path to root.

**Comment by jeremymeng** [comment] 2020-02-22 07:37
I opened PR #50 to use temp directory and random file names for decompilation documents.  After the change VS Code shouldn't try to save the files to the root directory.

@raghavg123 when the issue happened (two blank documents opened in VS Code), were you able to close them by clicking `X` button and choosing not to save them?  If not it might be a VS Code bug somewhere.

**Comment by raghavg123** [comment] 2020-02-22 07:41
> @raghavg123 when the issue happened (two blank documents opened in VS Code), were you able to close them by clicking `X` button and choosing not to save them? If not it might be a VS Code bug somewhere.

Yes. Also, when closing the whole window, only one Save popup showed up for either of both files which when passed ("Don't Save") closed both files, if that helps.

**Comment by jeremymeng** [comment] 2020-02-22 07:54
Got it. I am also seeing that even I can close them, the next time VS Code starts it loads them again.

**Comment by christophwille** [comment] 2020-04-02 08:41
@jeremymeng Any idea already how we can solve this?

**Comment by jeremymeng** [comment] 2020-04-02 16:11
Probably put dcompiled content in temp files in %TEMP% folder and save them. I haven't got time to try the repro of https://github.com/microsoft/vscode/issues/91220 in an insider build

**Comment by jeremymeng** [comment] 2020-04-04 07:18
I just merged #50 so we no longer use the `untitled` documents.

**Comment by Rpinski** [comment] 2021-10-30 08:11
Since we have stopped using temporary files with 3c1a220fcb0944cd7dfc2224be3180ef5ae58a0b, all those problems with re-opened files after startup should have gone since 0.12 release.

Please open a new issue if still anything strange happens.

**Closed by Rpinski** 2021-10-30 08:11 UTC
Labels: issue-bug
